### PR TITLE
[task4][redux] switch to themoviedb api

### PR DESCRIPTION
**Pull request by dubbha**

### CODE REVIEW

**Comment by itmoh** [comment]
"npm start" doesn't work.

**Comment by itmoh** [comment]
It would be better to separate redux store and actions from component.

**Comment by itmoh** [comment]
You can connect Films by block and make separate request for films on connect and update props. It will make getFIlm action simpler.

**Comment by dubbha** [comment]
> "npm start" doesn't work.

It does, if you run `npm run build` first: `npm run build && npm run prod`
Normally `build` is run once after `install` and then `start` is fired on each startup, serving from dist.
Will update README to be clear on this.

Done in [bac357](https://github.com/dubbha/remp/pull/5/commits/bac3571466a3314fabaca549156c0770d90dfe80)

**Comment by dubbha** [comment]
> It would be better to separate redux store and actions from component.

> You can connect Films by block and make separate request for films on connect and update props. It will make getFIlm action simpler.

Let's discuss these, I am not sure I fully understand.

**Comment by dubbha** [comment]
[7c3e69](https://github.com/dubbha/remp/pull/5/commits/7c3e69d883b415c4fc9575cb4a211b507578be57) fixes a case-sensitive typo which could cause build fail on Unix systems.
Also a link to an online now.sh deployment added to readme.

**Comment by dubbha** [comment]
common store implemented in [80242b7](https://github.com/dubbha/remp/pull/5/commits/80242b7b6fffe4a96bf04c417d9e2c4c2435fcf2)

**Comment by dubbha** [comment]
Switching from `title` to `id`  for movie identification in [d58c39](https://github.com/dubbha/remp/pull/5/commits/d58c39f70fa3ce0d93d2c83bf52187bf8736910c)

**Pull request merged**
